name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'readme.md'
  pull_request:

jobs:
  multi:
    uses: xoofx/.github/.github/workflows/dotnet-multi.yml@main
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}